version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
